ParadymeIntern/ParadymeIntern/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^RSR/', include('RSR.urls')),
    url(r'^$', RedirectView.as_view(url='RSR/main/', permanent=True)),
    url(r'^accounts/login/$', views.login, name ='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url('^accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ParadymeIntern/RSR/urls.py
from django.conf.urls import url
from django.contrib import admin
from. import views
from RSR.views import *

app_name = 'RSR'


urlpatterns = [

    url(r'^uploaddoc/$', uploaddoc, name='uploaddoc'),
    url(r'^uploadlist/$', uploadlist, name = 'uploadlist'),
    url(r'^listdelete/$', listdelete, name="listdelete"),
    url(r'^main/$', main, name = 'main'),
    url(r'^search/$', search, name='search'),
    url(r'^edit/(?P<person_id>\d+)/$', views.person_edit, name='person-edit'),
    url(r'^LA/$', linkanalysis, name='LA'),
    url(r'^logout/$', views.logout_page, name = 'logout'),

    #Search/Export Team
    url(r'^search/person_detail/(?P<pk>[0-9]+)/$', views.detail, name='detail'),


]

ParadymeIntern/RSR/forms.py
# -*- coding: utf-8 -*-
from django import forms
import os
from .models import *

class PersonForm(forms.ModelForm):

    class Meta:

        model = Person
        fields = '__all__'

class CommentsForm(forms.ModelForm):
	Comments = forms.CharField( widget=forms.Textarea )
	class Meta:
		model = Person
		fields =('Comments',)

class DocumentForm(forms.Form):
	pwd = os.path.dirname(__file__)
	with open(pwd+"/static/config/config.txt") as myfile:
		dataconfig="".join(line.rstrip() for line in myfile)
    
	docfile = forms.FileField(widget=forms.FileInput(attrs={'accept':dataconfig}),label='Select a file:')

ParadymeIntern/RSR/views.py
# -*- coding: utf-8 -*-
from .models import *
import docx2txt
from django.utils import timezone

# Create your views here.
#=======
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm

from RSR.models import *
from RSR.forms import *
from django.shortcuts import get_object_or_404
from django.contrib.auth import logout
from .filters import *
###Search #
from django.db.models import Q
from RSR.persondetails import Detail
from RSR.persondetails2 import Detail2
from django.views.generic.edit import UpdateView


### json Parsing ##
import json

###TESTING OCR
#from PIL import Image
#from wand.image import Image as IMG
#import pytesseract
#import textract
###
import networkx as nx
from networkx.drawing.nx_agraph import graphviz_layout
from networkx_viewer import Viewer
import pandas as pd
import nxviz as nv
import numpy as np
import matplotlib.pyplot as plt



def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def main(request):
    return render(request, 'main.html')

#def get_string(name):
#    img=Image.open(name)
#    utf8_text = pytesseract.image_to_string(img)
#    utf8_text = str(utf8_text.encode('ascii', 'ignore'))
#    return utf8_text


@login_required
def uploaddoc(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            temp_doc = Document(docfile=request.FILES['docfile'])

            #temp_doc.firstname = Document(docfile=request.POST.get('firstname'))
            #temp_doc.lastname = Document(docfile=request.POST.get('lastname'))
            #temp_doc.type = Document(docfile=request.POST.get('type'))
            temp_doc.firstname = request.POST['firstname']
            temp_doc.lastname = request.POST['lastname']
            temp_doc.type = request.POST['type']
            temp_doc.uploaduser = request.user.username

            temp_doc.save()

            if ".doc" in temp_doc.docfile.path:
                print (temp_doc.docfile.path)
                temp_doc.docfile.wordstr = parse_word_file(temp_doc.docfile.path)
                print (temp_doc.docfile.wordstr)
                temp_doc.save(update_fields=['wordstr'])

            else:

            #    temp_doc.docfile.wordstr = textract.process(temp_doc.docfile.path)

            #    if len(temp_doc.docfile.wordstr) < 50:
                img=IMG(filename=temp_doc.docfile.path,resolution=200)

                img.save(filename='temp.jpg')
                utf8_text = get_string('temp.jpg')
                os.remove('temp.jpg')

                print (utf8_text)
                temp_doc.docfile.wordstr = utf8_text
                temp_doc.save(update_fields=['wordstr'])

                print (temp_doc.docfile.wordstr)
                temp_doc.save(update_fields=['wordstr'])

            parsed_json  = parse_file(temp_do.docfile.wordstr)
            #json testing#
            #check for json file, wont be needed as parsing will return json#
            if ".json" in temp_doc.docfile.path:
                #either load json, or recieve json file
                js = json.load(open(temp_doc.docfile.path))
                #iterate through json file

                #initialize person out side of for loop/if statements so we can use it later
                person = Person(Name="temp")
                for label in js:

                    #Checking Labels to see which table to create
                    if label == "person":
                        for key in js[label]:
                            if key == "name":
                                person.Name = js[label][key]
                            elif key == "email":
                                person.Email = js[label][key]
                            elif key == "address":
                                person.Address = js[label][key]
                            elif key == "zipcode":
                                person.ZipCode = js[label][key]
                            elif key == "state":
                                person.State = js[label][key]
                            elif key == "phone":
                                person.PhoneNumber = js[label][key]
                            elif key == "linkedin":
                                person.Linkedin = js[label][key]
                            elif key == "github":
                                person.GitHub = js[label][key]
                        person.Resume = temp_doc.docfile
                        person.TypeResume = temp_doc.type
                        person.save()


                    elif label == "skills":
                        for key in js[label]:
                            #check to see if skill exists
                            query_set=Skills.objects.all()
                            query_set=query_set.filter(Name__icontains=key["skill"])
                            #if skill does not exist create skill
                            if not query_set:
                                query_set = Skills(Name = key["skill"])
                                query_set.save()
                            #if skill does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]
                            skill_to_person = PersonToSkills(SkillsID = query_set, PersonID = person,YearsOfExperience = key["YearsOfExperience"])
                            skill_to_person.save()

                    elif label == "work":
                        for key in js[label]:
                            #check to see if company exists
                            query_set=Company.objects.all()
                            query_set=query_set.filter(Name__icontains=key["company"])
                            #if company does not exist create skill
                            if not query_set:
                                query_set = Company(Name = key["company"])
                                query_set.save()
                            #if company does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]
                            #intermediary table stuff
                            company_to_person = PersonToCompany(CompanyID = query_set, PersonID = person,
                                Title = key["title"],
                                ExperienceOnJob = key["experience"],
                                StartDate = key["startDate"],
                                EndDate = key["endDate"],
                                Desc = key["summary"])
                            company_to_person.save()

                    elif label == "education":
                        for key in js[label]:
                            #check to see if School exists
                            query_set=School.objects.all()
                            query_set=query_set.filter(Name__icontains=key["school"]["name"]).filter(DegreeLevel = key["school"]["degreeLevel"])
                            #if School does not exist create skill
                            if not query_set:
                                query_set = School(Name = key["school"]["name"], DegreeLevel = key["school"]["degreeLevel"])
                                query_set.save()
                            #if School does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]

                            # NOW DO MAJOR
                            query_set_1=Major.objects.all()
                            query_set_1=query_set_1.filter(Name__icontains=key["major"]["major"]).filter(Dept__icontains = key["major"]["dept"]).filter(MajorMinor__icontains = key["major"]["major/minor"])
                            if not query_set_1:
                                query_set_1 = Major(Name = key["major"]["major"], Dept = key["major"]["dept"], MajorMinor = key["major"]["major/minor"])
                                query_set_1.save()
                            #if School does exist, grab first match from queryset
                            else:
                                query_set_1 = query_set_1[0]

                            #intermediary table stuff
                            ed_to_person = PersonToSchool(SchoolID = query_set, PersonID = person, MajorID = query_set_1,
                                GPA = key["GPA"],
                                GradDate = key["gradDate"])
                            ed_to_person.save()


                    elif label == "sideprojects":
                        for key in js[label]:
                            #check to see if project exists
                            query_set=SideProject.objects.all()
                            query_set=query_set.filter(Name__icontains=key["name"])
                            #if project does not exist create project
                            if not query_set:
                                query_set = SideProject(Name = key["name"])
                                query_set.save()
                            #if project does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]
                            #intermediary table stuff
                            project_to_person = PersonToSide(SideID = query_set, PersonID = person, Desc = key["description"])
                            project_to_person.save()

                    elif label == "award":
                        for key in js[label]:
                            #check to see if Award exists

ParadymeIntern/RSR/templates/acc_cont.html
{% extends 'navigation.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2 style = " text-decoration: underline;text-decoration-color: orange;font-family: 'Open Sans', Helvetica, Arial, sans-serif;">User Access Control</h2>

    </div>
</div>
  {% endblock %}

ParadymeIntern/RSR/templates/export.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Export</title>
</head>
<body>
    <p>
        <a href = "" >Export</a>
    </p>
</body>
</html>

ParadymeIntern/RSR/templates/index.html
{% extends 'navigation.html' %}

{% block content %}
    <body>

           <div class="inner cover">
             <h1 class="cover-heading" style = "font-family: Raleway, Arial">Upload your resume</h1>

             <br/>



             <form action="{% url 'RSR:uploaddoc' %}" method="post" enctype="multipart/form-data" align="center">
                         <div align="center">

             {% csrf_token %}
             <span class="btn btn-default btn-file">
                Browse 
                <input type="file">
                {{ form.non_field_errors }}
                {{ form.docfile.errors }}{{ form.docfile }}
                </span>

             <br/>

             <br/>
            <p></p>
                </div>

                

             
                    <input type="text" class="form-control" name = "firstname" id="firstname" style="width: 300px; margin:auto;" placeholder="First Name" />

                    <br/>
                       
                    <div style = "color:#FFF">
                    <input type="text" class="form-control" name = "lastname" id="lastname" style="width: 300px; margin:auto;" placeholder="Last Name"/>
                    <br/><br/>
                    <input type="radio" name="type" id="pi" value="Prospective Intern" style="margin-left: 12px; margin-right: 10px">Prospective Intern</input><br/>
                    <input type="radio" name="type" id="pe" value="Prospective Employee" style="margin-left: 39px;margin-right: 10px">Prospective Employee</input><br/>
                    <input type="radio" name="type" id="i" value="Intern" style="margin-left: -68px;margin-right: 10px">Intern</input><br/>
                    <input type="radio" name="type" id="e" value="Employee" style="margin-left: -41px;margin-right: 10px">Employee</input><br/>
                    <br/>
                    </div>
            <p></p>
                    <input class = "button-style" type="submit" value="Upload"/>
            </form>
            <p></p>


            <form action="{% url 'RSR:uploadlist' %}">
                                  <input class = "button-style" type="submit" value="Check the upload list" />
             </form>

           </div>
</body>


  {% endblock %}

ParadymeIntern/RSR/templates/linkanalysis.html
{% extends 'navigation.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2 style = " text-decoration: underline;text-decoration-color: orange;font-family: 'Open Sans', Helvetica, Arial, sans-serif;">Link Analysis</h2>

    </div>
</div>
  {% endblock %}

ParadymeIntern/RSR/templates/navigation.html
                   {%load static%}
                   <!DOCTYPE html>
                   <html lang="en">
                   <style>
                   
                    .personal {  
                      float:left; 
                      width:40%;
                      margin-left:-50px

                    }
                    .skills{  
                        float:right; width:60%;
                    }
                    .content{position:relative; top:-75px;}

                    @media screen and (max-width: 1200px) {
                    .personal {width: 100%; margin-left: 0px; padding-bottom: 30px;}
                    .skills   {width: 100%; margin-left: 0px;}
                    }
                    @media screen and (max-width: 765px ) {
                      .content  {top : 0px;  }
                    
                    }



                   .divider{
                    width:5px;
                    height:auto;
                    float:left;
                    }
                   @import url(https://fonts.googleapis.com/css?family=Raleway:100,400,700);

                   /* box */
                    .left{
                         width: 30%;
                         float: left;
                         text-align: right;
                    }

                    .right{
                        width: 65%;
                        margin-left: 10px;
                        float:left;
                    }
                    h3{
                        text-transform: none !important;
                    }
                   .box {
                      background:#F5F5F5  ;
                      width:30%;
                      margin:40px auto;
                      padding-top: 35px;
                      padding-bottom: 15px;
                    }


                    .effect1{
                         box-shadow: 0 0 40px #000;
                       }
                    .chk-box{
                    vertical-align: middle;
                    margin-right:10px;
                    }
                                       /*EDIT THIS FOR BACKGROUND CHANGE*/
                                       .background{
                      background: linear-gradient(to top, #141e30, #243b55); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                                       }
                                       /* upload button*/
                                       .btn-file {
                        position: relative;
                        overflow: hidden;
                    }
                    .btn-file input[type=file] {
                        position: absolute;
                        top: 0;
                        right: 0;
                        min-width: 100%;
                        min-height: 100%;
                        font-size: 100px;
                        text-align: right;
                        filter: alpha(opacity=0);
                        opacity: 0;
                        outline: none;
                        background: white;
                        cursor: inherit;
                        display: block;
                    }



                   /* LOGIN INFO */
                    .form {
                      border-radius: 25px;
                        font-family: Raleway, "Roboto", helvetica, arial, sans-serif;

                           position: relative;
                           top: 30%;
                           z-index: 1;
                           background: #e3e3e3;
                           max-width: 360px;
                           margin: auto;
 
                           padding: 45px;
                           text-align: center;
                           box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
                           }
                     .form button {
                      font-family: Raleway, "Roboto", helvetica, arial, sans-serif;

                       width: 75%;
                       height: 50%;
                       border: 0;
                       padding: 15px;
                       cursor: pointer;
                     }
 
                   /* table css */
                   @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100);

.body {
  font-family: Raleway, "Roboto", helvetica, arial, sans-serif;
  font-size: 16px;
  font-weight: 400;
  text-rendering: optimizeLegibility;
}

div.table-title {
   display: block;
  margin: auto;
  max-width: 600px;
  padding:5px;
  width: 100%;
}

.table-title h3 {
   color: #fafafa;
   font-size: 30px;
   font-weight: 400;
   font-style:normal;
   font-family: Raleway, "Roboto", helvetica, arial, sans-serif;
   text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
   text-transform:uppercase;
}


/*** Table Styles **/

.table-fill {
  background: white;
  border-radius:3px;
  border-collapse: collapse;
  margin: auto;
  padding:50px;
  width: 100%;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
  animation: float 5s infinite;
  border-spacing: 0 50px;}
 
th {
  color:#D5DDE5;;
  background:#1b1e24;
  border-bottom:4px solid #9ea7af;
  border-right: 1px solid #343a45;
  font-size:23px;
  font-weight: 100;
  padding:24px;
  text-align:left;
  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  vertical-align:middle;
}

th:first-child {
  border-top-left-radius:3px;
}
 
th:last-child {
  border-top-right-radius:3px;
  border-right:none;
}
  
tr {
  border-top: 1px solid #C1C3D1;
  border-bottom-: 1px solid #C1C3D1;
  color:#666B85;
  font-size:16px;
  font-weight:normal;
  text-shadow: 0 1px 1px rgba(256, 256, 256, 0.1);
}
 
tr:hover td {
  background:#4E5066;
  color:#FFFFFF;
  border-top: 1px solid #22262e;
  border-bottom: 1px solid #22262e;
}
 
tr:first-child {
  border-top:none;
}

tr:last-child {
  border-bottom:none;
}
 
tr:nth-child(odd) td {
  background:#EBEBEB;
}
 
tr:nth-child(odd):hover td {
  background:#4E5066;
}

tr:last-child td:first-child {
  border-bottom-left-radius:3px;
}
 
tr:last-child td:last-child {
  border-bottom-right-radius:3px;
}
 
td {
  background:#FFFFFF;
  padding:20px;
  text-align:left;
  vertical-align:middle;
  font-weight:300;
  font-size:18px;
  text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
  border-right: 1px solid #C1C3D1;
}

td:last-child {
  border-right: 0px;
}

th.text-left {
  text-align: left;
}

th.text-center {
  text-align: center;
}

th.text-right {
  text-align: right;
}

td.text-left {
  text-align: left;
}

td.text-center {
  text-align: center;
}

td.text-right {
  text-align: right;
}






                   .TextBox{
                     -moz-border-radius:1px;
                     -webkit-border-radius:1px;
                     border-radius:1px;
                     border: #solid 10px #000;
                     background-color: rgba(255,255,255,0.8);
                     height:100%;
                     width:100%;
                     margin-left: auto ;
                     margin-right: auto ;
                   }
                   .button-style{
    
                    -webkit-border-radius: 4px;
                    -moz-border-radius: 4px;
                    border-radius: 4px;
                    display: inline-block;
                    margin: 2px 0;
                    padding: 12px 25px;
                    background: none;
                    background-image: none;
                    background-color: #fdd200;
                    background-color: #ff7e00;
                    /* button color */
                    color: #ffffff;
                    vertical-align: middle;
                    text-align: center;
                    text-transform: uppercase;
                    letter-spacing: 1px;
                    font-weight: normal;
                    font-size: 13px;
                    font-family: Raleway, Montserrat, 'Open Sans', Helvetica, Arial, sans-serif;
                    line-height: 20px;
                    cursor: pointer;
                    -webkit-appearance: none;
                    border: 0px;
                    }

                   </style>
                   <head>

                       <meta charset="utf-8">
                       <meta http-equiv="X-UA-Compatible" content="IE=edge">
                       <meta name="viewport" content="width=device-width, initial-scale=1">
                       <meta name="description" content="">
                       <meta name="author" content="">

                       <title>RSR</title>

                       <!-- Bootstrap Core CSS -->
                       <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

                       <!-- Custom Fonts -->
                       <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
                       <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
                       <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

                       <!-- Theme CSS -->
                       <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

                       <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
                       <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
                       <!--[if lt IE 9]>
                           <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                           <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
                       <![endif]-->

                   </head>
<div class = "background">
<!-- Navigation -->
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="{% url 'RSR:main' %}">
                <img style = "width: auto; height: 25px;" src = "http://www.paradymemanagement.com/wp-content/uploads/2015/11/paradyme-green.png">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a href="{% url 'RSR:uploaddoc' %}" >Upload</a>
                </li>
                <li>
                    <a href="{% url 'RSR:search' %}">Search</a>
                </li>
  
                <li>
                    <a href="{% url 'logout' %}">Log Out</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<section style = "font-family: Raleway, Roboto, helvetica, arial, sans-serif;" id="about" class="container content-section text-center">
<div class = "content">
{% block content %}
{% endblock %}
</div>
</section>

<!-- Footer -->
<footer>
    <div class="container text-center">
        <p>Copyright &copy; Paradyme Management 2017</p>
    </div>
</footer>

<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

<!-- Theme JavaScript -->
<script src="{% static 'js/grayscale.min.js' %}"></script>

</body>
</div>
</html>

ParadymeIntern/RSR/templates/ocr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OCR</title>
</head>
<body>

    <p>
        <a href = "" >OCR</a>
    </p>

</body>
</html>

ParadymeIntern/RSR/templates/parsing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parsing</title>
</head>
<body>
    <p>
        <a href = "" >Parsing</a>
    </p>
</body>
</html>

ParadymeIntern/RSR/templates/uploadlist.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class = "body">
             <h2 class="cover-heading" style = "font-family: Raleway, Arial">Filter Files</h2>
             <p></p>
             <br />
<form method="get">
<div style = "color:#000" class = "row">
    <div class="form-group col-sm-4 col-md-4">

    {% render_field documents.form.firstname class="form-control" style=" width: 300px; margin:auto;" placeholder="First Name"%} 
    </div>
  <div class="form-group col-sm-4 col-md-4">

    {% render_field documents.form.lastname class="form-control" style=" width: 300px; margin:auto;" placeholder="Last Name"%} 
</div>

<div class="form-group col-sm-4 col-md-4">

    {% render_field documents.form.type style=" width: 300px; margin:auto;" class="form-control"%} 
    </div>
    </div>
    <br/>
<div style = "align: center"
      <button type="submit" class = "button-style">Search</button>
      </div>
      </form>
      <p></p>
      <br />
      <br />


           <div class="inner cover">
             <h4 class="cover-heading" style = "font-family: Raleway, Arial">File Repository</h2>

            <!-- LIST OF THE UPLOAD FILE-->
            <table class="table-fill">
            {% if documents %}
               <thead>
               
					<tr>
						<th style = "padding:14px;" class="text-left">Type</th>
						<th style = "padding:14px;" class="text-left">Name</th>
                        <th style = "padding:14px;" class="text-left">Upload User</th>
						<th style = "padding:14px;" class="text-left">File</th>
						<th style = "padding:14px;" class="text-left">Action</th>
					</tr>
               </thead>
			   <tbody class="table-hover">
                  {% for document in documents.qs %}
                    <tr>
                        <td style = "padding:14px;"class="text-left">{{document.type}} </td>
                        <td style = "padding:14px;"class="text-left">{{ document.firstname }} {{document.lastname}}</td>
                        <td style = "padding:14px;"class="text-left">{{document.uploaduser}} </td>
                        <td style = "padding:14px;"class="text-left"><a style = "color:#ff7e00;" href="{{ document.docfile.url }}">{{document.docfile}}</a></td>
                        <td style="text-align: center" >
                            <form action="{% url 'RSR:listdelete' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="docfile" value="{{ document.pk }}" />
                                <input onclick="return confirm('Are you sure you want to delete this file?')" class = "button-style" type="submit" value="Delete" />
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                    {% else %}
                <h3> No document saved in the database! </h3>
            {% endif %}
            </table>
            <p> </p>
            <!--back btn-->
               
               <a href="{% url 'RSR:uploaddoc' %}" class = "button-style" type="button"> Go Back</a>

            </p>
           </div>

            <script>
            function goBack() {
                window.history.back();
            }
            </script>
</div>
  {% endblock %}